export const Product_Request = "Product_Request"
export const Product_Success = "Product_success"
export const Product_Fail = "Product_Fail"
export const Product_Detials_Request = "Product_Detials_Request"
export const Product_Detials_Success = "Product_Detials_Success"
export const Product_Detials_Fail = "Product_Detials_Fail"